name: 'Typescript Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/typescript.yml"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Install NPM packages
        run: yarn install

      - name: Format Check
        run: yarn run format-check

      - name: Link
        run: yarn run lint

      - name: Test
        run: yarn test

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "::error:: Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
      # - name: Test with Buildx
      #   uses: docker/bake-action@v1.7.0
      #   with:
      #     targets: test